### PR TITLE
Defined protocol methods

### PR DESCRIPTION
**Pull request by lsdlabs**
## Reason ✨
Trello Card: [Home: Delegate / Pass Data Back from Add Event](https://trello.com/c/UTfLGZDQ)

## What I did ✅
I defined the add event delegate to send information back (or forward depending how you see it :D ), to the home screen  

## How I did it 🌀
Added definition to the AddEventViewController.swift

## How you can test it 🔬
It cannot be tested yet...it is just the delegate definition which must me later implemented

### CODE REVIEW

**Review by elle-gover — APPROVED** [review]
"MARK: // - Outlets" should be moved up to be above the IBOutlets ! 🍭

**Review by BritneyS — APPROVED** [review]
I approve!

**Review by BritneyS — CHANGES_REQUESTED** [review]
For code style: I think the properties should be listed under //MARK: Properties, and there should be a //MARK: Outlets marker. *imagine cake*

**Comment by lsdlabs** [comment]
FIXED: listed outlets first, then properties in all of the view controllers

**Review by BritneyS — APPROVED** [review]
I approve the changes!

**Pull request merged**
